feat(cms-base): regulation price displaying
shopware/frontends pull request #101
Opened 2023-04-03 12:07 UTC by mkucmus

closes: #94 

- [x] types enhancement
- [x] cms-base package adjusted
- [x] vue-demo-store adjusted
- [x] tier prices condition to avoid wrong price displaying
- [x] added missing tier prices on pdp built in cms-page 
- [x] check for other occurrences when regulation price can be displayed 
- [x] report found issues in the core

2023-04-05 08:27 UTC, patzick requested changes
Looks good, I have some questions for typing :)

if the regular price is always if calculatedPrice exist we could improve:

```ts
const regulationPrice = computed(() => price.value?.regulationPrice.price)
```

or even we can use it without computed directly in the template as it's not something which is reactive
```html
<div class="text-xs flex text-gray-500" v-if="price?.regulationPrice">
    Previously <SharedPrice class="ml-1" :value="price.regulationPrice.price"/>
</div>
```

2023-04-05 08:27 UTC, patzick commented on packages/cms-base/components/SwListingProductPrice.vue
> +const regulationPrice = computed(() => price?.value?.regulationPrice?.price)
```suggestion
const regulationPrice = computed(() => price.value?.regulationPrice?.price)
```
one too many :)

2023-04-05 08:27 UTC, patzick commented on packages/cms-base/components/public/cms/element/CmsElementBuyBox.vue
> +const regulationPrice = computed(() => price?.value?.regulationPrice?.price)
```suggestion
const regulationPrice = computed(() => price.value?.regulationPrice?.price)
```

2023-04-05 08:27 UTC, patzick commented on packages/types/shopware-6-client/models/checkout/cart/price/CalculatedPrice.d.ts
> +  regulationPrice: {
Does it mean it's always visible if calculated prices are visible?

2023-04-05 08:27 UTC, patzick commented on packages/types/shopware-6-client/models/framework/pricing/Price.d.ts
> +  regulationPrice: Partial<Price>;
not the same as in `CalculatedPrice`?

2023-04-05 10:22 UTC, mkucmus commented on packages/types/shopware-6-client/models/framework/pricing/Price.d.ts
> +  regulationPrice: Partial<Price>;
It's a different place and format :)

2023-04-06 06:56 UTC, patzick approved these changes

2023-04-06 06:56 UTC, merged