feat(vue-demo):  create state and country component
shopware/frontends pull request #270
Opened 2023-06-16 14:01 UTC by mdanilowicz

### Description
 closes #245 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Screenshots (if applicable)

### Additional context

2023-06-20 10:24 UTC, patzick requested changes
Nice work. Overall I'd go for extracting whole `SharedAddressForm`/`SharedAddressFields`, as the API of this component would be much simpler and validation rules would be handled in a single place as well instead of being passed as props. Additionally I left comment for simplification of data passing. Let me know what do you think about moving all address fields to single component

2023-06-20 10:24 UTC, patzick commented on templates/vue-demo-store/components/shared/SharedCountryStateInput.vue
> +};
using useVModels would make it more clean without keeping additional local state https://vueuse.org/core/useVModels/#usevmodels
```suggestion
const { countryId, stateId } = useVModels(props, emit)

const { getCountries, getStatesForCountry } = useCountries();

const states = computed(() => {
  return getStatesForCountry(countryId.value);
});

watch(countryId, () => {
  stateId.value = '';
}) // maybe with 'immediate'
```

2023-06-20 10:24 UTC, patzick commented on templates/vue-demo-store/components/shared/SharedCountryStateInput.vue
> +        @change="handleCountryUpdate"
then input handling is also easier
```suggestion
        v-model="countryId"
        required
        name="country"
        autocomplete="country-name"
        class="mt-1 block w-full p-2.5 border border-gray-300 text-gray-900 text-sm rounded-md shadow-sm focus:ring-brand-light focus:border-brand-light"
        data-testid="country-select"
```

2023-06-21 08:12 UTC, patzick commented
- component watchers are standard Vue3 solution - simple and reactive way to do something in response for a change in other reactive value(s)
- code is much cleaner, VueUse is now practically official set of composables for Vue3 + a lot of stuff from it is adapted into the Vue3 itfelf. We should use it as much as we can, so let's do it
- one thing before "magic" - storing additional local state is almost always ending with problems, when the data is changed in the parent (for example, some late loading/refresh/change address to edit) then suddenly your data is wrong as you have two sources of truth
- the "magic" is standard Vue way (same as first point) and the code is (again) much cleaner with proper responsibility
  - `v-model` is changing field value in parent
  - `watcher` for country value is resetting state value
  - a single place where field values are saved (in parent, where the data belongs)

So I'm still standing with previous review and suggestions, I hope that now you're more convinced though :)

2023-06-27 13:01 UTC, patzick requested changes
I see a pending review as the previous was dismissed, so setting it up for last comment

2023-06-30 09:07 UTC, patzick commented on templates/vue-demo-store/components/shared/SharedCountryStateInput.vue
> +};
Updated suggestion after the discussion:
```suggestion
const { countryId, stateId } = useVModels(props, emit)
const { getCountries, getStatesForCountry } = useCountries();
const states = computed(() => {
  return getStatesForCountry(countryId.value);
});

function onCountrySelectChanged() {
  stateId.value = '';
}
```

2023-06-30 09:08 UTC, patzick commented on templates/vue-demo-store/components/shared/SharedCountryStateInput.vue
> +        @change="handleCountryUpdate"
updated suggestion
```suggestion
        v-model="localCountry"
        required
        name="country"
        autocomplete="country-name"
        class="mt-1 block w-full p-2.5 border border-gray-300 text-gray-900 text-sm rounded-md shadow-sm focus:ring-brand-light focus:border-brand-light"
        data-testid="country-select"
        @change="onCountrySelectChanged"
```

2023-07-03 09:07 UTC, kstala approved these changes

2023-07-03 09:51 UTC, patzick approved these changes
great work!

2023-07-03 09:52 UTC, merged