Fix/cms text element
shopware/frontends pull request #283
Opened 2023-06-22 12:25 UTC by BrocksiNet

### Description
closes #275

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

### Screenshots (if applicable)

**Before:**
![grafik](https://github.com/shopware/frontends/assets/3763023/c8f81bb4-f307-4f45-b528-c6b195e96763)

**After:**
![grafik](https://github.com/shopware/frontends/assets/3763023/e438c310-20d0-4c5d-9153-7c998e5ded9e)

### Additional context
- Added possibilities to support colors from admin and align
- SSR: Still shows style="" and class="" after hard reload (did not find the root of that)
- CSR: HTML is mostly clean without empty style and class
- Config for UnoCSS is moved to a own config file because suggest by docu
- Added some base styles as preflights as example (and we miss them in demo store)

2023-06-23 08:34 UTC, mdanilowicz approved these changes

2023-06-23 08:34 UTC, mdanilowicz commented on packages/cms-base/components/public/cms/element/CmsElementText.vue
> +            newStyle = "color:" + styleColor + ";" + currentStyle;
```suggestion
            newStyle = `color:${styleColor};${currentStyle}`;
```

2023-06-23 08:34 UTC, mdanilowicz commented on packages/cms-base/components/public/cms/element/CmsElementText.vue
> +          const styleColor = node.attrs?.color ?? null;
```suggestion
          const styleColor = node?.attrs?.color;
```

2023-06-23 08:34 UTC, mdanilowicz commented on packages/cms-base/helpers/html-to-vue/getOptionsFromNode.ts
> +  }
```suggestion
const attrs = (Object.keys(node.attrs).length === 0)? null : {...node.attrs}
```
It should work like that :D But please test if you decide to use this one line :)

2023-06-27 13:11 UTC, patzick requested changes

2023-06-27 13:11 UTC, patzick commented on packages/cms-base/components/public/cms/element/CmsElementText.vue
> +        conditions(node: any) {
let's type it properly instead of `any`, here and in other places :)

2023-06-27 13:11 UTC, patzick commented on packages/cms-base/helpers/html-to-vue/getOptionsFromNode.ts
> +  style: String | null;
```suggestion
  align?: string;
  attrs?: Record<string, string>;
  class?: string;
  style?: string;
```
wouldn't be better to have it as undefined if not existing?

2023-06-28 14:32 UTC, BrocksiNet commented
I did my best to add your suggestions. :muscle: 
Thx for your feedback guys. :heart_decoration:

2023-06-29 18:24 UTC, merged