fix(cms): link building
shopware/frontends pull request #336
Opened 2023-07-21 16:19 UTC by mdanilowicz

### Description

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Screenshots (if applicable)

### Additional context

2023-07-24 06:28 UTC, BrocksiNet commented on packages/composables/src/helpers/urlIsAbsolute.ts
> +export default function getUrlPrefix(url: string) {
Is it good practice to name the default function different than the function where I use it?

2023-07-24 17:45 UTC, patzick requested changes

2023-08-07 07:13 UTC, BrocksiNet approved these changes
LGTM :+1:  and welcome back :wink:

2023-08-07 18:07 UTC, patzick approved these changes

2023-08-07 18:07 UTC, merged