feat(cms): add 3d media support
shopware/frontends pull request #794
Opened 2024-03-23 16:51 UTC by mdanilowicz

### Description

closes #748 

### Type of change

### ToDo's

### Screenshots (if applicable)

### Additional context

2024-04-02 13:38 UTC, BrocksiNet commented
How to know on which product the 3D model is placed or where to test (without searching via Admin).
Description is very incomplete :crying_cat_face:

2024-04-09 07:21 UTC, kstala approved these changes

2024-04-17 08:06 UTC, patzick requested changes
Looks very good!
Only one minor issue to solve - lazy loading component, to not include threejs library in every image component

2024-04-17 08:06 UTC, patzick commented on packages/cms-base/components/public/cms/element/CmsElementImage.vue
> +      <SwMedia3D :src="props.content.data.media.url" />
Let's make this component lazy loaded. Otherwise import from line `12` is always executed in every `CmeElementImage` even if it's a normal picture

2024-04-18 12:40 UTC, patzick approved these changes

2024-04-18 12:40 UTC, merged